In [112]:
import json
import numpy as np
import pandas as pd
import multiprocessing

from pymoo.optimize import minimize
from pymoo.core.callback import Callback
from pymoo.algorithms.moo.nsga3 import NSGA3
from pymoo.core.problem import ElementwiseProblem, StarmapParallelization
from pymoo.util.ref_dirs import get_reference_directions
from pymoo.operators.repair.rounding import RoundingRepair
from pymoo.operators.mutation.pm import PolynomialMutation
from pymoo.operators.sampling.rnd import IntegerRandomSampling
from pymoo.operators.crossover.pntx import SinglePointCrossover

In [113]:
# Read CSVs
df_classrooms = pd.read_csv("./datasets/clean/CaracterizaçãoDasSalasSmall.csv", sep=";", header=0)
df_classes = pd.read_csv("./datasets/clean/HorarioDeExemploSmall.csv", sep=";", header=0)

def get_characteristics(row):
  cols_with_x = [col for col in row.index if row[col] == "X"]
  return ", ".join(cols_with_x)

# Prepare df_classrooms
df_classrooms["caracteristicas"] = df_classrooms.apply(get_characteristics, axis=1)
df_classrooms = df_classrooms[["Nome sala", "Capacidade Normal", "caracteristicas"]]
df_classrooms = df_classrooms.rename(columns={"Nome sala":"Sala da aula", "Capacidade Normal":"Lotação", "caracteristicas":"Características reais da sala"})
print("df_classrooms len: ", len(df_classrooms))

# Prepare df_classes
df_classes["Sala da aula"] = ""
df_classes["Lotação"] = ""
df_classes["Características reais da sala"] = ""
print("df_classes len: ", len(df_classes))

df_classrooms len:  85
df_classes len:  5746


In [114]:
class ISCTE_CLASSES(ElementwiseProblem):
  def __init__(self, df_classes, df_classrooms, constraints=[500, 1300], **kwargs):
    self.df_classes = df_classes
    self.df_classrooms = df_classrooms
    self.constraints = constraints

    n_var = len(df_classes)

    xl = np.zeros(n_var)
    xu = np.array([len(df_classrooms) - 1] * len(df_classes))

    super().__init__(n_var=n_var, n_obj=3, n_ieq_constr=2, n_eq_constr=0, xl=xl, xu=xu, **kwargs)


  def _evaluate(self, x, out, *args, **kwargs):
    df_schedule = self.arr_to_df(x)
    schedule_eval = self.df_evaluate(df_schedule)

    superlotacao = schedule_eval[1]
    sobreposicao = schedule_eval[0]

    sobreposicao_const, superlotacao_const = self.constraints

    out["F"] = np.array(schedule_eval)
    out["G"] = [sobreposicao - sobreposicao_const, superlotacao - superlotacao_const]


  def arr_to_df(self, arr_schedule):
    df_schedule = self.df_classes.copy()

    for i, row in df_schedule.iterrows():
      if arr_schedule[i] >= 97:
        print(arr_schedule)

      classroom = self.df_classrooms.iloc[int(arr_schedule[i])]

      df_schedule.at[i, "Sala da aula"] = classroom.iloc[0]
      df_schedule.at[i, "Lotação"] = classroom.iloc[1]
      df_schedule.at[i, "Características reais da sala"] = classroom.iloc[2]

    df_schedule["Datetime Início"] = pd.to_datetime(df_schedule['Dia'] + ' ' + df_schedule['Início'], format='%d/%m/%Y %H:%M:%S')
    df_schedule["Datetime Fim"] = pd.to_datetime(df_schedule['Dia'] + ' ' + df_schedule['Fim'], format='%d/%m/%Y %H:%M:%S')
    df_schedule["Lotação - Inscritos no turno"] = df_schedule.apply(lambda x: int(x["Lotação"]) - int(x["Inscritos no turno"]), axis=1)

    return df_schedule


  def check_overlap(self, start, end, df):
    for _, row in df.iterrows():
      tmp_start = row["Datetime Início"]
      tmp_end = row["Datetime Fim"]

      if tmp_start <= start < tmp_end or tmp_start < end <= tmp_end:
        return True

    return False


  def df_evaluate(self, df):
    sobreposicao = 0
    superlotacao = (df["Lotação - Inscritos no turno"] < 0).sum()
    caracteristicas = df.apply(lambda row: row["Características da sala pedida para a aula"] not in row["Características reais da sala"], axis=1).sum()

    for i, row in df.iterrows():
      tmp_df = df.loc[i + 1:].copy()
      tmp_df = tmp_df[(tmp_df['Sala da aula'] == row['Sala da aula']) & (tmp_df['Dia'] == row['Dia'])].copy()

      if tmp_df.shape[0] > 0 and self.check_overlap(row["Datetime Início"], row["Datetime Fim"], tmp_df):
          sobreposicao += 1

    return [sobreposicao, superlotacao, caracteristicas]

In [115]:
class MyCallback(Callback):

  def __init__(self) -> None:
    super().__init__()


  def notify(self, algorithm):
    constraints = algorithm.problem.constraints

    for el in algorithm.pop.get("F"):
      constraints = self.update_constraints(constraints, el[0], el[1])

    algorithm.problem.constraints = constraints


  def update_constraints(self, constraints, sobreposicao, superlotacao):
    sobreposicao_const, superlotacao_const = constraints

    new_sobreposicao_const = sobreposicao if sobreposicao < sobreposicao_const else sobreposicao_const
    new_superlotacao_const = superlotacao if superlotacao < superlotacao_const else superlotacao_const

    return [new_sobreposicao_const, new_superlotacao_const]

In [116]:
# the number of process to be used
n_process = 6

# initialize the pool
pool = multiprocessing.Pool(n_process)

runner = StarmapParallelization(pool.starmap)

iscte_problem = ISCTE_CLASSES(df_classes, df_classrooms, elementwise_runner=runner)

ref_dirs = get_reference_directions("das-dennis", 3, n_partitions=13) # 13

nsga3 = NSGA3(
  pop_size=105, # 105
  ref_dirs=ref_dirs,
  sampling=IntegerRandomSampling(),
  crossover=SinglePointCrossover(prob=1),
  mutation=PolynomialMutation(prob=1, eta=10, repair=RoundingRepair()),
  eliminate_duplicates=True
)

iscte_res = minimize(
  iscte_problem,
  nsga3,
  seed=7,
  save_history=True,
  verbose=True,
  callback=MyCallback(),
  termination=('n_eval', 10500) # 315
)

print('Threads:', iscte_res.exec_time)

X = iscte_res.opt.get("X")
F = iscte_res.opt.get("F")

print(F)

n_gen  |  n_eval  | n_nds  |     cv_min    |     cv_avg    |      eps      |   indicator  
     1 |      105 |      6 |  0.000000E+00 |  2.429524E+01 |             - |             -
     2 |      210 |      6 |  0.000000E+00 |  2.155238E+01 |  0.000000E+00 |             f
     3 |      315 |      6 |  0.000000E+00 |  2.136190E+01 |  0.000000E+00 |             f
     4 |      420 |      6 |  0.000000E+00 |  2.111429E+01 |  0.000000E+00 |             f
     5 |      525 |      6 |  0.000000E+00 |  2.100000E+01 |  0.000000E+00 |             f
     6 |      630 |      6 |  0.000000E+00 |  2.024762E+01 |  0.000000E+00 |             f
     7 |      735 |      6 |  0.000000E+00 |  1.979048E+01 |  0.000000E+00 |             f
     8 |      840 |      6 |  0.000000E+00 |  1.950476E+01 |  0.000000E+00 |             f
     9 |      945 |      6 |  0.000000E+00 |  1.862857E+01 |  0.000000E+00 |             f
    10 |     1050 |      6 |  0.000000E+00 |  1.774286E+01 |  0.000000E+00 |             f

In [117]:
pool.close()

In [118]:
iscte_res.history[0].opt.get("F")

array([[ 481., 1273., 2445.],
       [ 496., 1240., 2483.],
       [ 476., 1283., 2397.],
       [ 499., 1251., 2423.],
       [ 470., 1284., 2452.],
       [ 463., 1295., 2473.]])

In [119]:
for i in [0, 9, 24, 49, 74, 99]:
  score_json = json.dumps(iscte_res.history[i].opt.get("F").tolist(), indent=4)
  schedule_json = json.dumps(iscte_res.history[i].opt.get("X").tolist(), indent=4)

  with open(f"./results/final/NSGA_III_constraint/score_gen_{i+1}.json", "w") as outfile:
    outfile.write(score_json)
    
  with open(f"./results/final/NSGA_III_constraint/schedule_gen_{i+1}.json", "w") as outfile:
    outfile.write(schedule_json)

In [120]:
# ==========================================================
# n_gen  |  n_eval  | n_nds  |      eps      |   indicator  
# ==========================================================
#      1 |      105 |      9 |             - |             -
#      2 |      210 |     11 |  0.0112359551 |         ideal
#      3 |      315 |     14 |  0.1111111111 |         ideal
# Threads: 447.20428824424744
# [[ 481. 1273. 2445.]
#  [ 496. 1240. 2483.]
#  [ 476. 1283. 2397.]
#  [ 499. 1251. 2423.]
#  [ 486. 1254. 2416.]
#  [ 470. 1328. 2429.]
#  [ 485. 1249. 2484.]
#  [ 508. 1237. 2414.]
#  [ 491. 1263. 2415.]
#  [ 508. 1291. 2396.]
#  [ 454. 1308. 2474.]
#  [ 500. 1231. 2476.]
#  [ 467. 1349. 2445.]
#  [ 485. 1270. 2427.]]

In [121]:
# result_dict = {"Score": F.tolist(), "Schedule": X.tolist()}

# results_json = json.dumps(result_dict, indent=4)

# with open("./results/NSGA_III_result_2_1.json", "w") as outfile:
#   outfile.write(results_json)